#photo , device_id, age, gender, satisfaction,created_by,created_at
#
# with this snippet from insight_in_face\migrations\0001_initial.py:
# # Generated by Django 4.1.1 on 2021-10-19 11:48
#
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.FloatField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('satisfaction', models.FloatField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'faces',
            },
        ),
    ]
#
